version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - printenv
      - AWS_ACC=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f5)
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACC.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  pre_build:
    commands:
      - REPOSITORY_URI=$AWS_ACC.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build . -t $REPOSITORY_URI/${REPO}:latest
      - echo Build completed on `date`
  post_build:
    commands:
      #- $(aws ecr get-login --region $AWS_REGION --no-include-email)
      #- aws ecr describe-repositories --registry-id ${AWS_ACC} --repository-name ${REPO}
      - docker push $REPOSITORY_URI/${REPO}:latest
      - echo {\"repo\":\"${REPO}\"} > repo.json
artifacts:
  files:
    # - target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
    - target/spring-petclinic-3.1.0.BUILD-SNAPSHOT.jar
    - repo.json